### ISSUE TITLE
FocalTech FLT0101

### ISSUE THREAD

**Issue by LongQT-sea** [chilledHamza/VoodooPS2FocalTech#1]
Hi
I have a FocalTech FLT0101 ps2 touchpad
Is it possible to add support to it?

**Comment by chilledHamza** [comment]
[ApplePS2SmartTouchPad.kext ](https://osxlatitude.com/forums/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/) supports FLT0101, but it's closed source.

It's possible to add support for FLT0101, But I don't have FLT0101, so I can't do it myself.

Best I can suggest is to try porting Linux driver ([focaltech.c](https://github.com/torvalds/linux/blob/master/drivers/input/mouse/focaltech.c), mostly code that parse the PS2 packet).

FTE0001 didn't have a Linux implementation either, I implemented new protocol on Linux first, made sure everything works as expected and then ported it to macOS. I call this new protocol FocalTech_v2
