### ISSUE TITLE
Trackpad click issue

### ISSUE THREAD

**Issue by hameez21** [chilledHamza/VoodooPS2FocalTech#2]
Hey bud i have the same y11c laptop.
The problem with this kext is i m unable to tap to left click

**Comment by chilledHamza** [comment]
There is no such problem, you have to enable "Tap to click" under Trackpad System Preference.
For other supported gestures, check [VoodooI2C Documentation](https://voodooi2c.github.io/#Supported%20Gestures/Supported%20Gestures)

**Comment by SyedHameez21** [comment]
bud I m seeing no trackpad found on trackpad settings but all the gestures are working fine be it 2 fingers or 3 fingers just tap to click isn't working

**Comment by chilledHamza** [comment]
Again that has nothing to do with this kernel extension. That should be a configuration issue (something is wrong in your EFI/config.plist).

From my past experience, Trackpad Preference pane doesn't show up if you don't have Battery Status Working. So, to access Trackpad preferences you have to get Battery working.

**Comment by hameez21** [comment]
Ya battery status is currently not working.
I tried using your efi bt the problem was that the open core would go into windows and doesnt even give me an option to boot mac

**Comment by chilledHamza** [comment]
macOS Version?

Edit: Currently only have macOS installed (earlier had triple boot), so I have boot-picker disabled. press and hold "ESC" right after selection Boot Media using F12 (Boot Menu). that will show Boot Picker, else you can modify config.plist to show always show boot picker.
I'll check config tonight, and update config.plist to show boot picker (update in the Guide). let me know if you have any other issue with my EFI.

**Comment by hameez21** [comment]
Thanks i will modify the config and let u know

**Comment by SyedHameez21** [comment]
Thanks to you everything is working using your efi.
There was a problem with wifi not working and not showing up in network settings.
I added few kext like intel Bluetootth firmware and 4 other kext I forgot the names got it working again

**Comment by chilledHamza** [comment]
Wi-Fi + BT should be working with my EFI, I included AirportItlwm.kext (Big Sur) along with IntelBluetoothInjector.kext
IntelBluetoothFirmware.kext isn't required, and Bluetooth works natively but "Turn off Bluetooth" button is grayed out (IntelBluetoothInjector.kext enables that Turn off/on Button)

If you are running Catalina or any other version of macOS then you have to replace AirportItlwm.kext with respective version, or use Itlwm.kext + Heliport instead (Itlwm will work with different versions of macOS)

**Edit: don't use AirportItlwm and Itlwm at same time
